name: 'Sample'
description: 'Sample of GitHub Actions'
inputs:
    username:
        description: "Username"
        requried: true
        default: "Hoge"
outputs:
    time:
        description: 'The time'
runs:
    using: 'node12'
    main: 'dist/index.js'
